---
profile::apps::samba::workgroup: FR.LAN
profile::apps::samba::users:
  'chris':
    password: 'Testing'
profile::apps::samba::shares:
  'Test':
    comment: 'Test Share'
    path: '/tmp'
    browsable: true


profile::os::monitor::influxdbinputs: 
  cpu:
    percpu: true
    totalcpu: true
  mem: {}
  io: {}
  net: {}
  disk: {}
  diskio: {}
  processes: {}
  swap: {}
  system: {}
  kernel: {}
